Solution
mate-academy/py-dictionary pull request #37
Opened 2022-06-08 14:38 UTC by Serhii-Leonenko

2022-06-09 06:48 UTC, RomaTsybulia approved these changes

2022-06-09 08:57 UTC, Serhii-Leonenko commented
pop __delittem__ work incorrect, i will try to fix them

2022-06-09 11:12 UTC, MasterpieceElbow requested changes

2022-06-09 11:12 UTC, MasterpieceElbow commented on app/main.py
> +    def pop(self, pop_key):
`pop` has an optional argument `defaultvalue`. Rework.

2022-06-10 07:05 UTC, MasterpieceElbow approved these changes

2024-11-06 14:21 UTC, closed without merging