Solution
mate-academy/py-dictionary pull request #67
Opened 2022-07-06 16:48 UTC by Splend1ed

2022-07-07 12:20 UTC, IvanRamyk commented on app/main.py
> +        for _ in self.hash_table:
Why use `for` loop here
When you don't know the number of iterations `while` is a more common solution

2022-07-08 06:24 UTC, Abnormaltype requested changes

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +                index += 1
It can be much more concise. It is relevant to use such incrementation:` index = (index + 1) % self.capacity`.

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +                index += 1
the same here

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +        else:
remove unnecessary `else`

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +        for i in self.hash_table:
what is `i`?

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +        return len(temp_ls)
why not `return self.length`?)

2022-07-08 06:24 UTC, Abnormaltype commented on app/main.py
> +                if hash(key) == self.hash_table[index][0] and\
create variable `hash_` and store `hash(key)`

2022-07-11 07:10 UTC, Abnormaltype requested changes

2022-07-11 07:10 UTC, Abnormaltype commented on app/main.py
> +        self.capacity = 8
what about `length`?

2022-07-11 07:10 UTC, Abnormaltype commented on app/main.py
> +        return len(temp_ls)
fix this please

2022-07-11 07:10 UTC, Abnormaltype commented on app/main.py
> +                    temp_list.append(item)
how to create a copy of `list`?)

2022-07-11 10:59 UTC, Abnormaltype approved these changes
well done!

2024-02-02 19:19 UTC, closed without merging